### PR TITLE
BugFix: Add CoinSupported configuration

### LINKED ISSUE #294: Request acocunt/coins always failed when using account-based rosetta implementation
**Describe the bug**
[One of the recent patches](https://github.com/coinbase/rosetta-cli/commit/dacb2494fde841def213ac08ae538a1171e0e00b) causes problem.
It always call `account/coins` when we run `check:construction`, but rosetta-ethereum(account-based blockchain) does not support that.

**To Reproduce**
Just run `check:construction` using `rosetta-ethereum`.

**Expected behavior**
When using account-based blockchain, `account/coins` must not be called.

### PR DESCRIPTION
**Pull request by aeharvlee**
Currently every check:construction tries to fetch coins but not every rosetta implementations support coin endpoint (e.g. rosetta-ethereum).

This PR Fixes #294 

### Motivation
* It can solve current problem (always trying to fetch `account/coins`).

### Solution
* Add configuration for indicating whether rosetta-implementation implements coins feature or not.

### CODE REVIEW

**Comment by aeharvlee** [comment]
@racbc @nasmithan 

Hi reviewers :) PTAL this PR and related issue.
Thanks

**Comment by cb-heimdall** [comment]
Review Error for shiatcb @ 2022-04-05 14:52:43 UTC
User must have write permissions to review

**Comment by shrimalmadhur** [comment]
@aeharvlee can you sign the commits. That's a required step before I can merge. Thank you!

**Comment by shiatcb** [comment]
@aeharvlee I made a copy to your PR so we can quickly merge and release: https://github.com/coinbase/rosetta-cli/pull/297 (don't worry, I linked to this original PR and @ your name). Please close this one. Thanks in advance!

**Comment by shrimalmadhur** [comment]
Closing this due to #297 . Thanks @aeharvlee for the PR, sorry we had to push it fast due to an urgent blocker. Appreciate the contribution though :)

**Pull request closed without merging**
